[package]
name = "float-diff"
version = "0.1.2"
license = "MIT"
edition = "2018"

description = "Utilities for use in calculating and summarizing differences between floating point values."
authors = ["Stony Lohr <stony.lohr@gmail.com>"]

[dependencies]
float-cmp = "0.8.0"
